[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.14.7"
dependencies = [
    "argon2-cffi>=25.1.0",
    "asyncpg>=0.31.0",
    "cachetools>=7.1.7",
    "fastapi-crons>=2.5.0",
    "fastapi[standard]>=0.139.2",
    "pydantic-settings>=2.14.2",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.51.0",
]

[tool.fastapi]
entrypoint = "src.main:app"

[tool.ruff.lint]
extend-select = ["COM812"]

[tool.ruff.format]
skip-magic-trailing-comma = false

[dependency-groups]
dev = [
    "ruff>=0.16.2",
]
